#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Levi Nelson"
email = "54561718+LeviticusNelson@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"

[[--scope]]
--when.repositories = ["/workspaces"]
[--scope.user]
email = "levi.nelson@calleridreputation.com"
[--scope.signing]
key = "~/.ssh/git-commit-signing/coder.pub"
